Feature/39523
UrvashiChaudhary/javascript-server pull request #12
Opened 2020-10-29 12:27 UTC by UrvashiChaudhary

Create a folder controllers inside src
Create folder user and trainee inside controllers.
Create following files in both folder
Controller.ts
routes.ts
index.ts

Define following routes in the trainee
get - /
post - /
put - /
delete - /

Define a class in Controller file having a method for each route returning some fake response.
Create a router.ts file in the root of src directory and import all the created routes and export them.
Import the router to the server file from router.ts file and use them in setUpRoutes method with /api prefix.

2020-11-04 08:32 UTC, adilsuccessive requested changes
Fix all lint issues

2020-11-04 08:32 UTC, adilsuccessive commented on src/controllers/trainee/Controller.ts
> +    get(req, res, next){
type of req, res and next missing.

2020-11-04 08:32 UTC, adilsuccessive commented on src/controllers/trainee/Controller.ts
> +    create(req, res, next){
type of req, res, next missing.

2020-11-04 08:32 UTC, adilsuccessive commented on src/controllers/trainee/Controller.ts
> +    update(req, res, next){
type missing.

2020-11-04 08:32 UTC, adilsuccessive commented on src/controllers/trainee/Controller.ts
> +    delete(req, res, next){
type missng.

2020-11-04 08:32 UTC, adilsuccessive commented on src/router.ts
> +const mainRouter =  Router();
type of mainRouter is missing.

2020-11-04 08:32 UTC, adilsuccessive commented on src/controllers/trainee/routes.ts
> +const traineeRouter = Router();
type of traineeRouter is missing.

2020-11-04 11:14 UTC, UrvashiChaudhary commented on src/controllers/trainee/Controller.ts
> +    get(req, res, next){
done

2020-11-04 11:14 UTC, UrvashiChaudhary commented on src/controllers/trainee/Controller.ts
> +    create(req, res, next){
done

2020-11-04 11:15 UTC, UrvashiChaudhary commented on src/controllers/trainee/Controller.ts
> +    update(req, res, next){
done

2020-11-04 11:15 UTC, UrvashiChaudhary commented on src/controllers/trainee/Controller.ts
> +    delete(req, res, next){
done

2020-11-04 11:15 UTC, UrvashiChaudhary commented on src/router.ts
> +const mainRouter =  Router();
done

2020-11-04 11:15 UTC, UrvashiChaudhary commented on src/controllers/trainee/routes.ts
> +const traineeRouter = Router();
done

2020-11-05 12:23 UTC, UrvashiChaudhary commented on src/controllers/trainee/Controller.ts
> +    get(req, res, next){
lint issues are resolved

2020-11-06 05:38 UTC, merged