Feature/40010
UrvashiChaudhary/javascript-server pull request #15
Opened 2020-11-04 13:23 UTC by UrvashiChaudhary

- Create a file Database.ts inside libs folder.
- Install npm package mongoose and @types/mongoose.
- Add MONGO_URL=mongodb://localhost:27017/express-training to your .env file.
- Create a class named Database inside Database.ts
- It will contain two methods(open and disconnect)
- open This method will accept mongoURL as argument and will establish a connection with mongodb.
- disconnect This method will close the connection with database.
- Use the method open to establish connection inside run method of class Server and only after successfull connection with 
- mongo app will start listening.

2020-11-16 05:31 UTC, adilsuccessive commented
Resolve conflicts

2020-11-17 05:00 UTC, UrvashiChaudhary commented
> Resolve conflicts

resolved

2020-11-17 06:55 UTC, adilsuccessive requested changes

2020-11-17 06:55 UTC, adilsuccessive commented on src/libs/validationHandler.ts
> +<<<<<<< HEAD
Resolve this conflict

2020-11-17 07:01 UTC, UrvashiChaudhary commented on src/libs/validationHandler.ts
> +<<<<<<< HEAD
resolved

2020-11-17 07:02 UTC, UrvashiChaudhary commented on src/libs/validationHandler.ts
> +<<<<<<< HEAD
resolved

2020-11-17 07:13 UTC, merged